[supervisord]
nodaemon=true
logfile=/var/www/html/storage/logs/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:webserver]
command=php artisan serve --host=0.0.0.0 --port=8000
directory=/var/www/html
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/webserver.log
stderr_logfile=/var/www/html/storage/logs/webserver.log

[program:worker]
command=php artisan queue:work --timeout=1800 --tries=1 --sleep=3
directory=/var/www/html
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/worker.log
stderr_logfile=/var/www/html/storage/logs/worker.log
